arch: 
   - amd64
   - ppc64le
go_import_path: github.com/kevinburke/ssh_config

language: go

go:
  - 1.11.x
  - 1.12.x
  - master
jobs:
 exclude:
  - arch: amd64
    go: 1.11.x
  - arch: amd64
    go: 1.12.x
  - arch: ppc64le
    go: 1.11.x
  - arch: ppc64le
    go: 1.12.x

before_script:
    - go get -u ./...

script:
    - make race-test
